In [1]:
# Two types of SQL connectors are being used in this tutorial 'sqlalchemy' (for select statements) 
# and 'pymysql' for inserts and update statements. 
# The 'conn' variable thats instantiated in the first cell is reused in subsequent cells, so in the event
# connection is lost in between, you may have to re-run the first cell to refresh that variable
# We are making a connection to the 'openmrs' MySQL database below using a username and password
import pymysql
import pandas as pd
import sqlalchemy


db_name = "openmrs"
db_host = "localhost"
db_username = "ub_dbmi_trg_usr"
db_password = "ub_20250202!"
conn = False
try:
    conn = sqlalchemy.create_engine('mysql+mysqlconnector://'+db_username+':'+db_password+'@'+db_host+'/'+db_name)
except Exception as err:
    print (err)
if conn:
    print ("connection to MySQL DB " + db_name + " successful.")
else:
    print ("connection error")

connection to MySQL DB openmrs successful.

In [2]:
#Below query can be used to find out the tables in the 'openmrs' DB.
df = pd.read_sql_query("show tables", conn)
#df.to_csv('c:\\temp\\openmrs_tables.csv', encoding='utf-8', index=False, header=True, mode='w')
# The 'to_csv' command should create a csv of all the tables in the 'show tables' command output
df.to_csv('openmrs_tables.csv', encoding='utf-8', index=False, header=True, mode='w')
df

                          Tables_in_openmrs
0    address_hierarchy_address_to_entry_map
1                   address_hierarchy_entry
2                   address_hierarchy_level
3                                   allergy
4                          allergy_reaction
..                                      ...
186                    visit_attribute_type
187                              visit_type
188            xforms_medical_history_field
189          xforms_person_repeat_attribute
190                            xforms_xform

[191 rows x 1 columns]

In [4]:
# The 'desc <table_name>' command should display the columns and their datatypes of the chosen <table_name>
df = pd.read_sql_query("desc person_name", conn)
#If you want to save this output as a csv the command can be used 
df.to_csv('person_name.csv', encoding='utf-8', index=False, header=True, mode='w')
df

                 Field          Type Null  Key Default           Extra
0       person_name_id           int   NO  PRI    None  auto_increment
1            preferred    tinyint(1)   NO            0
2            person_id           int   NO  MUL    None
3               prefix   varchar(50)  YES         None
4           given_name   varchar(50)  YES  MUL    None
5          middle_name   varchar(50)  YES  MUL    None
6   family_name_prefix   varchar(50)  YES         None
7          family_name   varchar(50)  YES  MUL    None
8         family_name2   varchar(50)  YES  MUL    None
9   family_name_suffix   varchar(50)  YES         None
10              degree   varchar(50)  YES         None
11             creator           int   NO  MUL       0
12        date_created      datetime   NO         None
13              voided    tinyint(1)   NO            0
14           voided_by           int  YES  MUL    None
15         date_voided      datetime  YES         None
16         void_reason  varchar(255)  YES         None
17          changed_by           int  YES         None
18        date_changed      datetime  YES         None
19                uuid      char(38)   NO  UNI    None

In [10]:
# SIMPLE SQL QUERY - WE ARE USING PANDAS TO PASS THE SQL QUERY AND THE conn VARIABLE FROM OUR FIRST CELL AS PARAMETERS
# TO THE read_sql_query() METHOD AND STORING THE RESULT SET AS A DATAFRAME IN MEMORY AND DISPLAYING IT
sql_query = "SELECT * "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " WHERE family_name = 'Shariff' "
df = pd.read_sql_query(sql_query, conn)
df

,person_name_id,preferred,person_id,prefix,given_name,middle_name,family_name_prefix,family_name,family_name2,family_name_suffix,degree,creator,date_created,voided,voided_by,date_voided,void_reason,changed_by,date_changed,uuid
0,182,0,182,None,Rebbecca,Jebuigut,None,Shariff,None,None,None,1,2006-01-18,0,None,None,None,None,None,de8293a6-1691-11df-97a5-7038c432aabf
1,569,0,569,None,Dian,Swega,None,Shariff,None,None,None,1,2006-01-18,0,None,None,None,None,None,de942686-1691-11df-97a5-7038c432aabf
2,2949,0,2949,None,Jully,Marenya,None,Shariff,None,None,None,1,2006-01-18,0,None,None,None,None,None,dea2c272-1691-11df-97a5-7038c432aabf
3,5901,0,5901,None,Lawfine,Akipoot,None,Shariff,None,None,None,1,2006-01-18,0,None,None,None,None,None,deb82e7f-1691-11df-97a5-7038c432aabf
4,8321,0,8321,None,Sheilah,Julie,None,Shariff,None,None,None,1,2006-01-18,0,None,None,None,None,None,deca5f07-1691-11df-97a5-7038c432aabf

In [ ]:
# SIMPLE SQL QUERY - GET person_id, NAME ATTRIBUTES, date_created FROM person_name WHERE person_id IS BETWEEN 9000 AND 9010 
sql_query = "SELECT person_id, given_name, middle_name, family_name, date_created "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " WHERE person_id > 9000 AND person_id < 9010 "
df = pd.read_sql_query(sql_query, conn)
df

   person_id given_name middle_name family_name date_created
0       9001   Arderson   Barmotony         Sun   2006-01-18
1       9004   Wilborne   Kipkoegei      Suluny   2006-01-18
2       9006    Aquelus     Shibaya     Muiruri   2006-01-18
3       9009   Florance     Makundi        Meto   2006-01-18

In [12]:
# LIKE OPERATOR
sql_query = "SELECT * "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " WHERE family_name LIKE '%Main%' "
df = pd.read_sql_query(sql_query, conn)
df

,person_name_id,preferred,person_id,prefix,given_name,middle_name,family_name_prefix,family_name,family_name2,family_name_suffix,degree,creator,date_created,voided,voided_by,date_voided,void_reason,changed_by,date_changed,uuid
0,406,0,406,None,Coreth,Kayasi,None,Main,None,None,None,1,2006-01-18,0,None,None,None,None,None,de840a2e-1691-11df-97a5-7038c432aabf
1,3319,0,3319,None,Ashley,Moni,None,Maina,None,None,None,1,2006-01-18,0,None,None,None,None,None,dea5ef65-1691-11df-97a5-7038c432aabf
2,3826,0,3826,None,Fatma,Shitaka,None,Maindi,None,None,None,1,2006-01-18,0,None,None,None,None,None,dea989e3-1691-11df-97a5-7038c432aabf
3,5463,0,5463,None,Lawrence,Kipng'Egtich,None,Main,None,None,None,1,2006-01-18,0,None,None,None,None,None,deb5b888-1691-11df-97a5-7038c432aabf
4,5516,0,5516,None,Sablon,Ngoyo,None,Maindi,None,None,None,1,2006-01-18,0,None,None,None,None,None,deb6592f-1691-11df-97a5-7038c432aabf
5,7047,0,7047,None,Satuta,Omwenga,None,Maindi,None,None,None,1,2006-01-18,0,None,None,None,None,None,dec18ea9-1691-11df-97a5-7038c432aabf
6,7798,0,7798,None,Daisylene,Khabukwe,None,Main,None,None,None,1,2006-01-18,0,None,None,None,None,None,dec692e6-1691-11df-97a5-7038c432aabf
7,8334,0,8334,None,Angelina,Mudoro,None,Main,None,None,None,1,2006-01-18,0,None,None,None,None,None,deca769b-1691-11df-97a5-7038c432aabf

In [ ]:
# ELIMINATING DUPLICATES COMPARE TO NEXT QUERY
sql_query = "SELECT DISTINCT family_name "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " WHERE family_name LIKE '%Main%' "
df = pd.read_sql_query(sql_query, conn)
df

  family_name
0        Main
1       Maina
2      Maindi

In [14]:
# ELIMINATING DUPLICATES COMPARE TO PREVIOUS QUERY
sql_query = "SELECT family_name "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " WHERE family_name LIKE '%Main%' "
df = pd.read_sql_query(sql_query, conn)
df

  family_name
0        Main
1        Main
2        Main
3        Main
4       Maina
5      Maindi
6      Maindi
7      Maindi

In [16]:
# ORDERING RESULTS
sql_query = "SELECT person_id, given_name, middle_name, family_name, date_created "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " WHERE family_name = 'Ali'  "
sql_query = sql_query + " ORDER BY date_created, given_name "
df = pd.read_sql_query(sql_query, conn)
df

   person_id given_name middle_name family_name date_created
0       3809   Dipporah    Epakhany         Ali   2006-01-18
1       2763   Dominick       Isabo         Ali   2006-01-18
2       9012      Lilly   Cheptanui         Ali   2006-01-18

In [ ]:
# ORDERING RESULTS
sql_query = "SELECT DISTINCT middle_name "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " ORDER BY middle_name "
df = pd.read_sql_query(sql_query, conn)
df

     middle_name
0           None
1
2              A
3           Abdi
4     Abdirahman
...          ...
2704       Zavai
2705        Zedy
2706       Zenah
2707      Zizame
2708    Znaliaka

[2709 rows x 1 columns]

In [20]:
# ORDERING RESULTS
sql_query = "SELECT middle_name "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " ORDER BY person_id "
df = pd.read_sql_query(sql_query, conn)
df

     middle_name
0
1
2              L
3              D
4           None
...          ...
5295        None
5296        None
5297           C
5298        None
5299        None

[5300 rows x 1 columns]

In [ ]:
# ORDERING RESULTS
# ORDER BY CLAUSE NEEDS TO BE IN SELECT LIST
sql_query = "SELECT DISTINCT middle_name "
sql_query = sql_query + " FROM person_name "
sql_query = sql_query + " ORDER BY person_id "
df = pd.read_sql_query(sql_query, conn)
df

DatabaseError: (mysql.connector.errors.DatabaseError) 3065 (HY000): Expression #1 of ORDER BY clause is not in SELECT list, references column 'openmrs.person_name.person_id' which is not in SELECT list; this is incompatible with DISTINCT
[SQL: SELECT DISTINCT middle_name  FROM person_name  ORDER BY person_id ]
(Background on this error at: https://sqlalche.me/e/20/4xp6)

In [ ]:
# KEYS AND FOREIGN KEYS
# LETS LOOK AT THE obs TABLE
sql_query = "DESC obs "
df = pd.read_sql_query(sql_query, conn)
df
# IN THE OPENMRS DATABASE, 'concept' DESCRIBES THE OBSERVAIONS/VISITS
# person_id AND concept_id ARE FOREIGN KEYS TO THE obs TABLE

                      Field           Type Null  Key Default           Extra
0                    obs_id            int   NO  PRI    None  auto_increment
1                 person_id            int   NO  MUL    None
2                concept_id            int   NO  MUL       0
3              encounter_id            int  YES  MUL    None
4                  order_id            int  YES  MUL    None
5              obs_datetime       datetime   NO  MUL    None
6               location_id            int  YES  MUL    None
7              obs_group_id            int  YES  MUL    None
8          accession_number   varchar(255)  YES         None
9            value_group_id            int  YES         None
10              value_coded            int  YES  MUL    None
11      value_coded_name_id            int  YES  MUL    None
12               value_drug            int  YES  MUL    None
13           value_datetime       datetime  YES         None
14            value_numeric         double  YES         None
15           value_modifier     varchar(2)  YES         None
16               value_text           text  YES         None
17                 comments   varchar(255)  YES         None
18                  creator            int   NO  MUL       0
19             date_created       datetime   NO         None
20                   voided     tinyint(1)   NO            0
21                voided_by            int  YES  MUL    None
22              date_voided       datetime  YES         None
23              void_reason   varchar(255)  YES         None
24            value_complex  varchar(1000)  YES         None
25                     uuid       char(38)   NO  UNI    None
26         previous_version            int  YES  MUL    None
27  form_namespace_and_path   varchar(255)  YES         None
28                   status    varchar(16)   NO        FINAL
29           interpretation    varchar(32)  YES         None

In [ ]:
# JOINS
# person_id AND concept_id COLUMNS IN THE obs TABLE ARE FOREIGN KEYS 
# IF WE WANTED TO LOOK AT THE OBSERVATIONS FOR A PATIENT BASED ON person_id
# WE SHOULD JOIN THE obs, person_name, AND concept_name TABLES
sql_query = "select obs.person_id, pn.given_name, pn.middle_name, pn.family_name, con.name as concept_name, obs_datetime"
sql_query = sql_query + " FROM obs " 
sql_query = sql_query + " LEFT JOIN person_name pn ON obs.person_id = pn.person_id " 
sql_query = sql_query + " LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
sql_query = sql_query + " WHERE obs.person_id in (50)" 
df = pd.read_sql_query(sql_query, conn)
df

,person_id,given_name,middle_name,family_name,concept_name,obs_datetime
0,50,Melvine,Nyangara,Busio,SCHEDULED VISIT,2006-04-18
1,50,Melvine,Nyangara,Busio,PAY CATEGORY,2006-04-18
2,50,Melvine,Nyangara,Busio,NEW COMPLAINTS,2006-04-18
3,50,Melvine,Nyangara,Busio,INTERVAL COMPLAINTS,2006-04-18
4,50,Melvine,Nyangara,Busio,ANTIRETROVIRAL USE,2006-04-18
5,50,Melvine,Nyangara,Busio,BLOOD OXYGEN SATURATION,2006-04-18
6,50,Melvine,Nyangara,Busio,SpO2,2006-04-18
7,50,Melvine,Nyangara,Busio,SAO2,2006-04-18
8,50,Melvine,Nyangara,Busio,DIASTOLIC BLOOD PRESSURE,2006-04-18
9,50,Melvine,Nyangara,Busio,DBP,2006-04-18
10,50,Melvine,Nyangara,Busio,DBP,2006-04-18
11,50,Melvine,Nyangara,Busio,DIASTOLIC,2006-04-18
12,50,Melvine,Nyangara,Busio,PULSE,2006-04-18
13,50,Melvine,Nyangara,Busio,HR,2006-04-18
14,50,Melvine,Nyangara,Busio,HEART RATE,2006-04-18
15,50,Melvine,Nyangara,Busio,HR,2006-04-18
16,50,Melvine,Nyangara,Busio,SYSTOLIC BLOOD PRESSURE,2006-04-18
17,50,Melvine,Nyangara,Busio,SBP,2006-04-18
18,50,Melvine,Nyangara,Busio,SBP,2006-04-18
19,50,Melvine,Nyangara,Busio,SYSTOLIC,2006-04-18
20,50,Melvine,Nyangara,Busio,TEMPERATURE (C),2006-04-18
21,50,Melvine,Nyangara,Busio,TEMP (C),2006-04-18
22,50,Melvine,Nyangara,Busio,TEMP (C),2006-04-18
23,50,Melvine,Nyangara,Busio,WEIGHT (KG),2006-04-18
24,50,Melvine,Nyangara,Busio,WT,2006-04-18
25,50,Melvine,Nyangara,Busio,CURRENT WHO HIV STAGE,2006-04-18
26,50,Melvine,Nyangara,Busio,NEW WHO/CDC STAGING CRITERIA MET,2006-04-18
27,50,Melvine,Nyangara,Busio,RETURN VISIT DATE,2006-04-18
28,50,Melvine,Nyangara,Busio,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-04-18
29,50,Melvine,Nyangara,Busio,PATIENT REPORTED CURRENT PCP PROPHYLAXIS,2006-04-18
30,50,Melvine,Nyangara,Busio,PATIENT REPORTED CURRENT TUBERCULOSIS PROPHYLAXIS,2006-04-18
31,50,Melvine,Nyangara,Busio,CURRENT TB PROPHYLAXIS,2006-04-18
32,50,Melvine,Nyangara,Busio,PATIENT REPORTED CURRENT TUBERCULOSIS TREATMENT,2006-04-18
33,50,Melvine,Nyangara,Busio,CURRENT TB TREATMENT,2006-04-18
34,50,Melvine,Nyangara,Busio,ANTIRETROVIRAL PLAN,2006-04-18
35,50,Melvine,Nyangara,Busio,ARV PLAN,2006-04-18
36,50,Melvine,Nyangara,Busio,CRYPTOCOCCAL TREATMENT PLAN,2006-04-18
37,50,Melvine,Nyangara,Busio,PCP PROPHYLAXIS PLAN,2006-04-18
38,50,Melvine,Nyangara,Busio,TUBERCULOSIS PROPHYLAXIS PLAN,2006-04-18
39,50,Melvine,Nyangara,Busio,TUBERCULOSIS TREATMENT PLAN,2006-04-18

In [ ]:
# MORE JOINS
# THE name COLUMN OF concept_name TABLE DOES NOT PROVIDE ENOUGH INFORMATION, IN CASE WE WANTED A MORE DETAILED DESCRIPTON OF THE VISIT 
# WE CAN INCLUDE ANOTHER TABLE concept_description. THE concept_id COLUMN IS A FOEIGN KEY IN THE concept_description TABLE.  
sql_query = "select obs.person_id, pn.given_name, pn.middle_name, pn.family_name, con.name as concept_name, cd.description as concept_desc, obs_datetime"
sql_query = sql_query + " FROM obs" 
sql_query = sql_query + " LEFT JOIN person_name pn ON obs.person_id = pn.person_id" 
sql_query = sql_query + " LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
sql_query = sql_query + " LEFT JOIN concept_description cd on obs.concept_id = cd.concept_id"
sql_query = sql_query + " WHERE obs.person_id in (50)" 
df = pd.read_sql_query(sql_query, conn)
# THIS LINE SAVES THE RESULT SET AS A FILE SINCE JUPYTER NOTEBOOK DISPLAY IS TRUNCATED. 
df.to_csv('concept_description_example.csv', encoding='utf-8', index=False, header=True, mode='w')
# YOU SHOULD BE ABLE TO SEE THE FILE, concept_description_example.csv, IN THE LEFT HAND PANE ONCE YOU RUN THIS CELL
# IF YOU HAVE THE FILE OPEN AND RUN THE CELL YOU MAY GET A PERMISSION DENIED ERROR, SO CLOSE THE FILE BEFORE YOU (RE)RUN THE CELL.
df

,person_id,given_name,middle_name,family_name,concept_name,concept_desc,obs_datetime
0,50,Melvine,Nyangara,Busio,SCHEDULED VISIT,Question on encounter form: asks whether the ...,2006-04-18
1,50,Melvine,Nyangara,Busio,PAY CATEGORY,"Question on encounter form. Defines the ""pay ...",2006-04-18
2,50,Melvine,Nyangara,Busio,NEW COMPLAINTS,Complaints since the last visit to the clinic....,2006-04-18
3,50,Melvine,Nyangara,Busio,INTERVAL COMPLAINTS,Complaints since the last visit to the clinic....,2006-04-18
4,50,Melvine,Nyangara,Busio,ANTIRETROVIRAL USE,"Question on encounter form: ""Is the patient c...",2006-04-18
5,50,Melvine,Nyangara,Busio,BLOOD OXYGEN SATURATION,"Oxygen saturation, as measured from a peripher...",2006-04-18
6,50,Melvine,Nyangara,Busio,SpO2,"Oxygen saturation, as measured from a peripher...",2006-04-18
7,50,Melvine,Nyangara,Busio,SAO2,"Oxygen saturation, as measured from a peripher...",2006-04-18
8,50,Melvine,Nyangara,Busio,DIASTOLIC BLOOD PRESSURE,A patient's diastolic blood pressure measureme...,2006-04-18
9,50,Melvine,Nyangara,Busio,DBP,A patient's diastolic blood pressure measureme...,2006-04-18
10,50,Melvine,Nyangara,Busio,DBP,A patient's diastolic blood pressure measureme...,2006-04-18
11,50,Melvine,Nyangara,Busio,DIASTOLIC,A patient's diastolic blood pressure measureme...,2006-04-18
12,50,Melvine,Nyangara,Busio,PULSE,"Patient pulse rate, as measured with a periphe...",2006-04-18
13,50,Melvine,Nyangara,Busio,HR,"Patient pulse rate, as measured with a periphe...",2006-04-18
14,50,Melvine,Nyangara,Busio,HEART RATE,"Patient pulse rate, as measured with a periphe...",2006-04-18
15,50,Melvine,Nyangara,Busio,HR,"Patient pulse rate, as measured with a periphe...",2006-04-18
16,50,Melvine,Nyangara,Busio,SYSTOLIC BLOOD PRESSURE,A patient's systolic blood pressure measuremen...,2006-04-18
17,50,Melvine,Nyangara,Busio,SBP,A patient's systolic blood pressure measuremen...,2006-04-18
18,50,Melvine,Nyangara,Busio,SBP,A patient's systolic blood pressure measuremen...,2006-04-18
19,50,Melvine,Nyangara,Busio,SYSTOLIC,A patient's systolic blood pressure measuremen...,2006-04-18
20,50,Melvine,Nyangara,Busio,TEMPERATURE (C),Patient's temperature in degrees centigrade.,2006-04-18
21,50,Melvine,Nyangara,Busio,TEMP (C),Patient's temperature in degrees centigrade.,2006-04-18
22,50,Melvine,Nyangara,Busio,TEMP (C),Patient's temperature in degrees centigrade.,2006-04-18
23,50,Melvine,Nyangara,Busio,WEIGHT (KG),Patient's weight in kilograms.,2006-04-18
24,50,Melvine,Nyangara,Busio,WT,Patient's weight in kilograms.,2006-04-18
25,50,Melvine,Nyangara,Busio,CURRENT WHO HIV STAGE,Question asked on encounter form. Expects a n...,2006-04-18
26,50,Melvine,Nyangara,Busio,NEW WHO/CDC STAGING CRITERIA MET,Question on encounter form. Describes whether...,2006-04-18
27,50,Melvine,Nyangara,Busio,RETURN VISIT DATE,Patient is to return on this date,2006-04-18
28,50,Melvine,Nyangara,Busio,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,Question on encounter form. Other current med...,2006-04-18
29,50,Melvine,Nyangara,Busio,PATIENT REPORTED CURRENT PCP PROPHYLAXIS,Question on encounter form. Other current med...,2006-04-18
30,50,Melvine,Nyangara,Busio,PATIENT REPORTED CURRENT TUBERCULOSIS PROPHYLAXIS,Question on encounter form. Other current med...,2006-04-18
31,50,Melvine,Nyangara,Busio,CURRENT TB PROPHYLAXIS,Question on encounter form. Other current med...,2006-04-18
32,50,Melvine,Nyangara,Busio,PATIENT REPORTED CURRENT TUBERCULOSIS TREATMENT,Question on encounter form. Other current med...,2006-04-18
33,50,Melvine,Nyangara,Busio,CURRENT TB TREATMENT,Question on encounter form. Other current med...,2006-04-18
34,50,Melvine,Nyangara,Busio,ANTIRETROVIRAL PLAN,Question on encounter form. Collects informat...,2006-04-18
35,50,Melvine,Nyangara,Busio,ARV PLAN,Question on encounter form. Collects informat...,2006-04-18
36,50,Melvine,Nyangara,Busio,CRYPTOCOCCAL TREATMENT PLAN,Question on encounter form. Collects informati...,2006-04-18
37,50,Melvine,Nyangara,Busio,PCP PROPHYLAXIS PLAN,Question on encounter form. Collects informat...,2006-04-18
38,50,Melvine,Nyangara,Busio,TUBERCULOSIS PROPHYLAXIS PLAN,Question on encounter form. Collects informati...,2006-04-18
39,50,Melvine,Nyangara,Busio,TUBERCULOSIS TREATMENT PLAN,Question on encounter form. Collects informati...,2006-04-18

In [ ]:
# EXCERCISE - COMPLETE LINE 5 AND 6 AND UNCOMMENT THEM
# GET ALL OBSERVATIONS WHERE CONCEPT_NAME IS RELATED TO (USE LIKE '%%') CRYPTOCOCCUS - SHOULD GET 14422 ROWS
sql_query = "select distinct obs_id, obs.person_id, con.name as concept_name, obs_datetime"
sql_query = sql_query + " FROM obs" 
#sql_query = sql_query + " LEFT JOIN concept_name con ON " 
#sql_query = sql_query + " WHERE "
df = pd.read_sql_query(sql_query, conn)
df

,obs_id,person_id,concept_name,obs_datetime
0,18,3718,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-02-08
1,49,3598,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-02-06
2,93,2656,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-02-09
3,152,3718,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-02-08
4,185,2159,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-02-08
...,...,...,...,...
14417,476826,3730,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-06-16
14418,476854,8050,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-06-16
14419,476886,6922,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-06-16
14420,476912,6146,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-06-16
14421,476950,3952,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,2006-10-04

In [47]:
# CALCULATE AGE FROM BIRTHDATE
sql_query = "SELECT person_id, birthdate, TIMESTAMPDIFF(YEAR, birthdate, CURDATE()) AS age"
sql_query = sql_query + " FROM PERSON " 
sql_query = sql_query + " WHERE  birthdate IS NOT NULL" 
sql_query = sql_query + " LIMIT 10 " 
df = pd.read_sql_query(sql_query, conn)
df

   person_id   birthdate  age
0       9348  1931-04-01   94
1       9347  1931-05-01   94
2       9349  1931-06-01   94
3          2  1941-05-01   84
4       3200  1950-01-05   75
5       8519  1950-01-05   75
6       6896  1950-01-10   75
7       7541  1950-01-11   75
8       3220  1950-02-07   75
9       2605  1950-02-14   75

In [48]:
# AGGREGATION
# CALCLUATE AVERAGE AGE OF MALES IN THE PERSON TABLE
sql_query = "SELECT AVG(TIMESTAMPDIFF(YEAR, birthdate, CURDATE())) AS avg_age"
sql_query = sql_query + " FROM PERSON " 
sql_query = sql_query + " WHERE  gender = 'M'" 
df = pd.read_sql_query(sql_query, conn)
df

   avg_age
0  50.3681

In [49]:
# AGGREGATION
# COUNT OF PERSONS OF AGE 80 AND OVER
sql_query = "SELECT COUNT(*) AS COUNT"
sql_query = sql_query + " FROM PERSON " 
sql_query = sql_query + " WHERE  TIMESTAMPDIFF(YEAR, birthdate, CURDATE()) >= 80" 
df = pd.read_sql_query(sql_query, conn)
df

   COUNT
0      4

In [ ]:
# EXCERCISE - COMPLETE LINES 4 AND 6 AND UNCOMMENT THEM - YOU SHOULD GET 476544 AS THE COUNT
# SIMPLE AGGREGATION
# FIND THE TOTAL NO. OF OBSERVATIONS IN THE YEAR 2006
#sql_query = "SELECT "
sql_query = sql_query + " FROM obs " 
#sql_query = sql_query + " WHERE  " 
df = pd.read_sql_query(sql_query, conn)
df

   TOTAL_OBS
0     476544

In [ ]:
# GROUPING AND AGGREGATION
# FIND THE COUNT OF ALL OBSERVATION/VISIT TYPES FOR PATIENT/PERSON NO. 18 AND SORT THEM IN DESCENDING ORDER OF FREQUENCY
sql_query = "SELECT person_id, con.name,cd.description, COUNT(*)"
sql_query = sql_query + " FROM obs " 
sql_query = sql_query + " LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
sql_query = sql_query + " LEFT JOIN concept_description cd ON obs.concept_id = cd.concept_id" 
sql_query = sql_query + " WHERE person_id IN (18)" 
sql_query = sql_query + " GROUP BY  person_id, con.name, cd.description" 
sql_query = sql_query + " ORDER BY COUNT(*) DESC" 
df = pd.read_sql_query(sql_query, conn)
df

,person_id,name,description,COUNT(*)
0,18,CURRENT ANTIRETROVIRAL DRUGS USED FOR TREATMENT,"Question on encounter forms: ""Is the patient c...",9
1,18,SBP,A patient's systolic blood pressure measuremen...,6
2,18,DBP,A patient's diastolic blood pressure measureme...,6
3,18,HR,"Patient pulse rate, as measured with a periphe...",6
4,18,TEMP (C),Patient's temperature in degrees centigrade.,6
5,18,SCHEDULED VISIT,Question on encounter form: asks whether the ...,3
6,18,CURRENT TB TREATMENT,Question on encounter form. Other current med...,3
7,18,DISCORDANT COUPLE,"Question on encounter form: ""Discordant couple?""",3
8,18,NEW COMPLAINTS,Complaints since the last visit to the clinic....,3
9,18,INTERVAL COMPLAINTS,Complaints since the last visit to the clinic....,3
10,18,ANTIRETROVIRAL USE,"Question on encounter form: ""Is the patient c...",3
11,18,PRIMARY REGIMEN,"Question on encounter form: ""Is this the patie...",3
12,18,ANTIRETROVIRAL ADHERENCE IN PAST WEEK,"Question on encounter form: ""During the last s...",3
13,18,ARV ADHERENCE,"Question on encounter form: ""During the last s...",3
14,18,OVERALL DRUG ADHERENCE IN LAST MONTH,"Question on encounter form: ""During the last m...",3
15,18,DIASTOLIC BLOOD PRESSURE,A patient's diastolic blood pressure measureme...,3
16,18,DIASTOLIC,A patient's diastolic blood pressure measureme...,3
17,18,ANTIRETROVIRAL PLAN,Question on encounter form. Collects informat...,3
18,18,ARV PLAN,Question on encounter form. Collects informat...,3
19,18,PULSE,"Patient pulse rate, as measured with a periphe...",3
20,18,HEART RATE,"Patient pulse rate, as measured with a periphe...",3
21,18,SYSTOLIC BLOOD PRESSURE,A patient's systolic blood pressure measuremen...,3
22,18,SYSTOLIC,A patient's systolic blood pressure measuremen...,3
23,18,CRYPTOCOCCAL TREATMENT PLAN,Question on encounter form. Collects informati...,3
24,18,PCP PROPHYLAXIS PLAN,Question on encounter form. Collects informat...,3
25,18,TUBERCULOSIS PROPHYLAXIS PLAN,Question on encounter form. Collects informati...,3
26,18,TUBERCULOSIS TREATMENT PLAN,Question on encounter form. Collects informati...,3
27,18,REFERRALS ORDERED,Question on encounter form. Answers are refer...,3
28,18,TEMPERATURE (C),Patient's temperature in degrees centigrade.,3
29,18,PATIENT REPORTED CURRENT CRYPTOCOCCUS TREATMENT,Question on encounter form. Other current med...,3
30,18,PATIENT REPORTED CURRENT PCP PROPHYLAXIS,Question on encounter form. Other current med...,3
31,18,PATIENT REPORTED CURRENT TUBERCULOSIS PROPHYLAXIS,Question on encounter form. Other current med...,3
32,18,CURRENT TB PROPHYLAXIS,Question on encounter form. Other current med...,3
33,18,PATIENT REPORTED CURRENT TUBERCULOSIS TREATMENT,Question on encounter form. Other current med...,3
34,18,PAY CATEGORY,"Question on encounter form. Defines the ""pay ...",2
35,18,WEIGHT (KG),Patient's weight in kilograms.,2
36,18,WT,Patient's weight in kilograms.,2
37,18,CD4,Measure of CD4 (T-helper cells) in blood,2
38,18,CD8,Measure of CD8 (T-Suppressor or killer cells) ...,2
39,18,RETURN VISIT DATE,Patient is to return on this date,2
40,18,PREGNANCY STATUS,"Question on encounter form: ""Is the patient pr...",2
41,18,CONCEPTION SINCE LAST VISIT,"Question on encounter form: ""Has she delivered...",2
42,18,BLOOD OXYGEN SATURATION,"Oxygen saturation, as measured from a peripher...",2
43,18,SpO2,"Oxygen saturation, as measured from a peripher...",2
44,18,SAO2,"Oxygen saturation, as measured from a peripher...",2
45,18,CURRENT WHO HIV STAGE,Question asked on encounter form. Expects a n...,2
46,18,NEW WHO/CDC STAGING CRITERIA MET,Question on encounter form. Describes whether...,2
47,18,HEIGHT (CM),Patient's height in centimeters.,1
48,18,HT,Patient's height in centimeters.,1
49,18,CD4 COUNT,Measure of CD4 (T-helper cells) in blood,1
50,18,CD3+CD4+ABS CNT,Measure of CD4 (T-helper cells) in blood,1
51,18,CD4%,Percentage of T-helper lymphocytes.,1
52,18,CD3+CD4+%LYMPH,Percentage of T-helper lymphocytes.,1
53,18,CD4 PERCENT,Percentage of T-helper lymphocytes.,1
54,18,CD8 COUNT,Measure of CD8 (T-Suppressor or killer cells) ...,1
55,18,CD3+CD8+ABS CNT,Measure of CD8 (T-Suppressor or killer cells) ...,1
56,18,PATIENT HOSPITALIZED,Question on encounter form. Answer is locatio...,1

In [55]:
# MORE GROUP BY AND AGGREGATION
# FIND ALL PATIENTS WHO HAVE HAD A HEART RATE MEASUREMENT IN OBSERVATIONS TABLE AND SORT THEM IN DESCENDING ORDER 
# ACCORDING TO THE TOTAL OBSERVATIONS
sql_query = "SELECT person_id,count(*)"
sql_query = sql_query + " FROM obs " 
sql_query = sql_query + " LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
sql_query = sql_query + " where con.name in ('HEART RATE') AND obs.value_numeric is not null" 
sql_query = sql_query + " GROUP BY  person_id" 
sql_query = sql_query + " ORDER BY COUNT(*) DESC" 
df = pd.read_sql_query(sql_query, conn)
df

      person_id  count(*)
0          2429        11
1          2159        10
2          2563        10
3            75        10
4          2375         9
...         ...       ...
5262       8688         1
5263       7143         1
5264       7394         1
5265       4416         1
5266       3952         1

[5267 rows x 2 columns]

In [ ]:
# EXCERCISE - COMPLETE LINES 4, 7, 9 AND UNCOMMENT THEM
# FIND COUNT OF ALL OBSERVATIONS, MIN HEART RATE AND AND MAX HEART RATE (USE COLUMN value_numeric)
# FOR PERSON IDS 2429, 2159, 2563 AND ORDER BY DESCENDING ORDER OF MAX HEART RATE
#sql_query = "SELECT person_id, "
sql_query = sql_query + " FROM obs " 
sql_query = sql_query + " LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
#sql_query = sql_query + " where person_id in ()" 
sql_query = sql_query + " GROUP BY  person_id" 
#sql_query = sql_query + " ORDER BY " 
df = pd.read_sql_query(sql_query, conn)
df 
#RESULT SHOULD LOOK LIKE BELOW
#person_id	Total_Obs	Min_Heart_Rate	Max_Heart_Rate
#	2429	11	58.0	93.0
#	2159	10	87.0	87.0
#	2563	10	54.0	71.0

   person_id  Total_Obs  Min_Heart_Rate  Max_Heart_Rate
0       2429         11            58.0            93.0
1       2159         10            87.0            87.0
2       2563         10            54.0            71.0

In [69]:
# HAVING CLAUSE
# FIND MOST FREQUENT VISIT TYPES BY PATIENT THOSE PATIENTS GREATER THAN 60 YRS OF AGE
sql_query = "SELECT obs.person_id, TIMESTAMPDIFF(YEAR, p.birthdate, CURDATE()) AS age, con.name as concept_name, count(*)"
sql_query = sql_query + " FROM obs " 
sql_query = sql_query + " LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
sql_query = sql_query + " LEFT JOIN person p ON obs.person_id = p.person_id" 
sql_query = sql_query + " WHERE TIMESTAMPDIFF(YEAR, p.birthdate, CURDATE()) >= 60" 
sql_query = sql_query + " GROUP BY  obs.person_id, con.name HAVING age >= 60" 
sql_query = sql_query + " ORDER BY person_id, COUNT(*) DESC" 
df = pd.read_sql_query(sql_query, conn)
df

,person_id,age,concept_name,count(*)
0,24,63,CURRENT ANTIRETROVIRAL DRUGS USED FOR TREATMENT,6
1,24,63,DBP,4
2,24,63,HR,4
3,24,63,SBP,4
4,24,63,TEMP (C),4
...,...,...,...,...
82692,9347,94,BACK PAIN,1
82693,9347,94,BACKACHE,1
82694,9347,94,LUMBAGO,1
82695,9348,94,CONFUSION,1
82696,9349,94,DEPRESSED,1

In [ ]:
# QUANTIFIERS
# FIND ALL OBSERVATION TYPES FOR PATIENTS OVER THE AGE OF 75
sql_query = "SELECT DISTINCT con.name as concept_name"
sql_query = sql_query + " FROM obs " 
sql_query = sql_query + " LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
sql_query = sql_query + " LEFT JOIN person p ON obs.person_id = p.person_id" 
sql_query = sql_query + " WHERE TIMESTAMPDIFF(YEAR, p.birthdate, CURDATE()) >= 80" 
sql_query = sql_query + " ORDER BY con.name" 
df = pd.read_sql_query(sql_query, conn)
df

  concept_name
0    BACK PAIN
1     BACKACHE
2    CONFUSION
3    DEPRESSED
4      LUMBAGO

In [ ]:
# NESTED QUERIES - LINES 7-10 ARE PART OF THE NESTED QUERY   
# FIND ALL PATIENTS WHO HAVE HAD A HEIGHT MEASUREMEMENT AND A WEIGHT MEASUREMENT
sql_query = "SELECT DISTINCT person_id"
sql_query = sql_query + " FROM obs " 
sql_query = sql_query + " LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
sql_query = sql_query + " WHERE con.name IN ('WT', 'WEIGHT (KG)') AND VALUE_NUMERIC IS NOT NULL AND person_id IN (" 
sql_query = sql_query + "   SELECT DISTINCT person_id" 
sql_query = sql_query + "   FROM obs" 
sql_query = sql_query + "   LEFT JOIN concept_name con ON obs.concept_id = con.concept_id" 
sql_query = sql_query + "   WHERE con.name IN ('HT', 'HEIGHT (CM)') AND VALUE_NUMERIC IS NOT NULL" 
sql_query = sql_query + "   ) " 
sql_query = sql_query + " ORDER BY obs.person_id " 
df = pd.read_sql_query(sql_query, conn)
df

     person_id
0           18
1          123
2          397
3          705
4          845
..         ...
635       9321
636       9329
637       9330
638       9342
639       9345

[640 rows x 1 columns]